### ISSUE TITLE
Simplify context menu

### ISSUE THREAD

**Issue by Xevrac** [Xevrac/cnc_backend#8]
Move Log Level and Tools into 

| Settings |
|   |   Tools
|   |   |   Generate.. 
|   |   Log Level
|   |   |   Only High...

**Comment by tecno14** [comment]
Done?

**Comment by Xevrac** [comment]
[9c7d852](https://github.com/Xevrac/cnc_backend/commit/9c7d85269638c1225f4318e85037489825564c9c)

**Comment by Xevrac** [comment]
Should have autoclosed @tecno14
